# test file

version = 0

[filesystem]
name = 'foo'
mountpoint = '/tmp/test'
threads = 0

[fuse]
posix-acl = false
async-read = true
message-size = 256

[func]
inode-calc = 'hybrid-hash'
symlinkify = false
symlinkify-timeout = 0
xattr = 'passthrough'

[func.access]
policy = 'ff'

[func.create]
policy = 'ff'

[func.getattr]
policy = 'ff'
follow-symlinks = 'never'

[func.rmdir]
policy = 'all'
follow-symlinks = 'never'

[func.link]
policy = 'all' # 'preserve-paths' | 'create-paths' | 'per-branch'
exdev = 'passthrough'

[func.write]
policy = 'null'
move-on-enospc = 'mfs'

[func.release]
drop-cache = true

[func.read]
policy = 'null'

[func.getxattr]
security-capability = false

[func.setxattr]
security-capability = false

[func.open]
link-cow = true
nfs-hack = 'off'

[func.rename]
policy = 'all'
exdev = 'passthrough'

[func.statfs]
policy = 'base'
ignore = 'none'

[func.readdir]
policy = 'posix'
readdirplus = false

[cache]
files = 'off'
statfs = 0
attr-timeout = 0
entry-timeout = 0
negative-entry-timeout = 0
writeback = false
symlinks = false
readdir = false

[[branch]]
enabled = true
name = 'foo'
type = 'literal'
path = '/mnt/hdd/foo'
mode = 'RO'

[[branch]]
enabled = true
name = 'bar'
type = 'literal'
path = '/mnt/hdd/foo'
mode = 'RW'

[[branch]]
enabled = true
name = 'ssds'
type = 'glob'
path = '/mnt/ssd/*'
order = 'name:asc' # | size
mode = 'RW'

# scan type: look for paths with a '.mergerfs' file or xattr?
[[branch]]
name = 'asdf'
type = 'scan'
path = '*'

[[branch.group]]
name = 'asdf'
branches = ['ssds']
func.create.policy = 'ep'
func.create.option0 = 'blah'
func.open.policy = 'ff'

[branches]
min-free-space = 123

[branches.tier.0]
[[branches.tier.0.branch]]
name = 'branch0'
type = 'scan'
path = '*'
order = 'name:asc' # | size
[[branches.tier.0.branch]]
name = 'branch1'
type = 'literal'
path = '/mnt/branch1'
[[branches.tier.0.branch]]
active = true
path = '/tmp/mergerfs/a'
path-type = 'literal'
mode = 'RW'
if-not-mountpoint = 'fail' # 'fail' | 'deactivate' ?

[branches.tier.1]
[[branches.tier.1.branch]]
name = 'branch0'
type = 'literal'
path = 'foo'
